name: Build and test Django activity applications

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '42 5 3 * *'

jobs:
  test:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - docker
          - podman
        runs-on:
          - ubuntu-24.04-arm
          - ubuntu-26.04-arm
    steps:
      - uses: actions/checkout@v7
      - run: make build docker=${{ matrix.runtime }}
      - run: make run docker=${{ matrix.runtime }}
      - run: make test docker=${{ matrix.runtime }}
