name: Check that we know about latest Django release

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '20 6 * * 5'

jobs:
  django-version-check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -s https://www.djangoproject.com/ > djangoproject.html
          grep 'Download.*latest release' djangoproject.html
          grep 'Download.*latest release: 4\.1\b' djangoproject.html
